version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgress-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  redisdb:
    image: redis:7.0
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDISPASS}"]

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight-container
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redisdb

  rabbitMQ:
    image: rabbitmq:latest
    container_name: rabbitmq-container
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQUSER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQPASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network


volumes:
  pg_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
